image: cznic/ubuntu:16.04

variables:
  DEBIAN_FRONTEND: noninteractive
  LC_ALL: C.UTF-8
  
amd64_build:
  stage: build
  script:
    - make -k all
  tags:
    - docker
    - linux
    - amd64

amd64_test:
  stage: test
  script:
    - make -k check
  tags:
    - docker
    - linux
    - amd64

deckard:
  stage: test
  before_script:
    - git submodule update --init --recursive
  script:
    - mkdir -p tests/deckard/contrib/libswrap/obj
    - PREFIX=$(pwd)/.local make all install
    - LD_LIBRARY_PATH=$(pwd)/.local/lib make -s -C tests/deckard/ TESTS=sets/resolver DAEMON=$(pwd)/.local/sbin/kresd
  tags:
    - docker
    - linux
    - amd64

#arm_build:
#  image: cznic/armhf-ubuntu:16.04
#  stage: build
#  script:
#    - make -k all
#  tags:
#    - docker
#    - linux
#    - arm

#arm_test:
#  image: armv7/armhf-ubuntu:16.04
#  stage: test
#  script:
#    - make -k check
#  tags:
#    - docker
#    - linux
#    - arm
