image: cznic/ubuntu:16.04

variables:
  DEBIAN_FRONTEND: noninteractive
  LC_ALL: C.UTF-8
  PREFIX: $CI_PROJECT_DIR/.local
  GIT_SUBMODULE_STRATEGY: recursive
  
build:linux:amd64:
  stage: build
  script:
    - make -k all
    - make install
  artifacts:
    untracked: true
  tags:
    - docker
    - linux
    - amd64

test:linux:amd64:
  stage: test
  script:
    - make -k check
  dependencies:
    - build:linux:amd64
  tags:
    - docker
    - linux
    - amd64

deckard:linux:amd64:
  stage: test
  script:
    - MAKEFLAGS="--jobs $(nproc) --keep-going" make check-integration
  dependencies:
    - build:linux:amd64
  tags:
    - docker
    - linux
    - amd64

respdiff:linux:amd64:
  stage: test
  before_script:
    - cp $(pwd)/resolver-benchmarking/response_differences/misc/policy-rc.d /usr/sbin/policy-rc.d
    - apt-get -qq update
    - apt-get -yqq install unbound bind9 runit dnsutils
    - echo "# configuration for GitLab CI .local builds" > /etc/ld.so.conf.d/local.conf
    - echo "$CI_PROJECT_DIR/.local/lib" >> /etc/ld.so.conf.d/local.conf
    - echo "$CI_PROJECT_DIR/.local/lib/$(dpkg-architecture -qDEB_HOST_MULTIARCH)" >> /etc/ld.so.conf.d/local.conf
    - ldconfig
  script:
    - resolver-benchmarking/response_differences/service/run $CI_PROJECT_DIR/resolver-benchmarking/response_differences/service 3 # time in seconds for servers to settle in
    - sv status $CI_PROJECT_DIR/resolver-benchmarking/response_differences/service/unbound $CI_PROJECT_DIR/resolver-benchmarking/response_differences/service/named $CI_PROJECT_DIR/resolver-benchmarking/response_differences/service/kresd
    - tail $CI_PROJECT_DIR/resolver-benchmarking/response_differences/service/unbound/log/current $CI_PROJECT_DIR/resolver-benchmarking/response_differences/service/named/log/current $CI_PROJECT_DIR/resolver-benchmarking/response_differences/service/kresd/log/current
    - python2.7 $(pwd)/resolver-benchmarking/response_differences/respdif -c $CI_PROJECT_DIR/resolver-benchmarking/response_differences/config/test.cfg -i $CI_PROJECT_DIR/resolver-benchmarking/response_differences/data/datafile-100k --json -o -b ${CI_COMMIT_REF_NAME}
    - $(pwd)/resolver-benchmarking/response_differences/nightly.sh
    - cp -r $(pwd)/resolver-benchmarking/response_differences/results $(pwd)
  dependencies:
    - build:linux:amd64
  artifacts:
    when: always
    expire_in: '1 week'
    paths:
      - results/*.json
      - results/*.out
      - results/*.log
  tags:
    - docker
    - linux
    - amd64
  allow_failure: true

#arm_build:
#  image: cznic/armhf-ubuntu:16.04
#  stage: build
#  script:
#    - make -k all
#  tags:
#    - docker
#    - linux
#    - arm

#arm_test:
#  image: armv7/armhf-ubuntu:16.04
#  stage: test
#  script:
#    - make -k check
#  tags:
#    - docker
#    - linux
#    - arm
