image: debian:stretch-slim

variables:
  DEBIAN_FRONTEND: noninteractive
  LC_ALL: C.UTF-8
  PREFIX: $CI_PROJECT_DIR/.local
  BASE_DEPS: build-essential bsdmainutils git ca-certificates dns-root-data
  SLIM_DEPS: libgnutls28-dev libjansson-dev libknot-dev liblmdb-dev libluajit-5.1-dev libuv1-dev luajit pkg-config
  FULL_DEPS: python doxygen python-breathe python-sphinx lua-sec lua-socket lua-http lua-mmdb libedit-dev libfstrm-dev libprotobuf-c-dev protobuf-c-compiler libgeoip-dev libhiredis-dev libmemcached-dev libcmocka-dev libsystemd-dev python-dnspython python-yaml
  DECKARD_DEPS: cmake
  
build:linux:amd64:
  stage: build
  before_script:
    - sed -i 's/deb\.debian\.org/ftp.cz.debian.org/g' /etc/apt/sources.list
    - apt-get -qq update
    - apt-get -qq dist-upgrade
    - apt-get -qq install $BASE_DEPS $SLIM_DEPS
  script:
    - make -k all
    - make install
  artifacts:
    untracked: true
  tags:
    - linux
    - amd64

build-full:linux:amd64:
  stage: build
  before_script:
    - sed -i 's/deb\.debian\.org/ftp.cz.debian.org/g' /etc/apt/sources.list
    - apt-get -qq update
    - apt-get -qq dist-upgrade
    - apt-get -qq install $BASE_DEPS $SLIM_DEPS $FULL_DEPS
  script:
    - make -k all
  artifacts:
    untracked: true
  tags:
    - linux
    - amd64

test:linux:amd64:
  stage: test
  before_script:
    - sed -i 's/deb\.debian\.org/ftp.cz.debian.org/g' /etc/apt/sources.list
    - apt-get -qq update
    - apt-get -qq dist-upgrade
    - apt-get -qq install $BASE_DEPS $SLIM_DEPS $FULL_DEPS
  script:
    - make -k check
  dependencies:
    - build-full:linux:amd64
  tags:
    - linux
    - amd64

deckard:linux:amd64:
  stage: test
  before_script:
    - sed -i 's/deb\.debian\.org/ftp.cz.debian.org/g' /etc/apt/sources.list
    - apt-get -qq update
    - apt-get -qq dist-upgrade
    - apt-get -qq install $BASE_DEPS $SLIM_DEPS $FULL_DEPS $DECKARD_DEPS
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - MAKEFLAGS="--jobs $(nproc) --keep-going" make check-integration
  dependencies:
    - build:linux:amd64
  tags:
    - linux
    - amd64

respdiff:linux:amd64:
  stage: test
  before_script:
    - sed -i 's/deb\.debian\.org/ftp.cz.debian.org/g' /etc/apt/sources.list
    - apt-get -qq update
    - apt-get -qq dist-upgrade
    - apt-get -qq install $BASE_DEPS $SLIM_DEPS $FULL_DEPS $DECKARD_DEPS
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - cp $(pwd)/resolver-benchmarking/response_differences/misc/policy-rc.d /usr/sbin/policy-rc.d
    - apt-get -qq update
    - apt-get -qq install unbound bind9 runit dnsutils
    - echo "# configuration for GitLab CI .local builds" > /etc/ld.so.conf.d/local.conf
    - echo "$CI_PROJECT_DIR/.local/lib" >> /etc/ld.so.conf.d/local.conf
    - echo "$CI_PROJECT_DIR/.local/lib/$(dpkg-architecture -qDEB_HOST_MULTIARCH)" >> /etc/ld.so.conf.d/local.conf
    - ldconfig
  script:
    - resolver-benchmarking/response_differences/service/run $CI_PROJECT_DIR/resolver-benchmarking/response_differences/service 3 # time in seconds for servers to settle in
    - sv status $CI_PROJECT_DIR/resolver-benchmarking/response_differences/service/unbound $CI_PROJECT_DIR/resolver-benchmarking/response_differences/service/named $CI_PROJECT_DIR/resolver-benchmarking/response_differences/service/kresd
    - tail $CI_PROJECT_DIR/resolver-benchmarking/response_differences/service/unbound/log/current $CI_PROJECT_DIR/resolver-benchmarking/response_differences/service/named/log/current $CI_PROJECT_DIR/resolver-benchmarking/response_differences/service/kresd/log/current
    - echo "UNBOUND" && dig +retry=1 +time=5 IN DNSKEY . -p 50001 @127.0.0.1
    - echo "BIND"    && dig +retry=1 +time=5 IN DNSKEY . -p 50002 @127.0.0.1
    - echo "KRESD"   && dig +retry=1 +time=5 IN DNSKEY . -p 50003 @127.0.0.1
    - python2.7 $(pwd)/resolver-benchmarking/response_differences/respdif -c $CI_PROJECT_DIR/resolver-benchmarking/response_differences/config/test.cfg -i $CI_PROJECT_DIR/resolver-benchmarking/response_differences/data/datafile-100k --json -o -b ${CI_COMMIT_REF_NAME}
    - $(pwd)/resolver-benchmarking/response_differences/nightly.sh
    - cp -r $(pwd)/resolver-benchmarking/response_differences/results $(pwd)
  dependencies:
    - build:linux:amd64
  artifacts:
    when: always
    expire_in: '1 week'
    paths:
      - results/*.json
      - results/*.out
      - results/*.log
      - resolver-benchmarking/response_differences/service/*/log/@*
  only:
    - tags
    - triggers
    - respdiff
    - respdiff-*
  tags:
    - linux
    - amd64
  allow_failure: true

#arm_build:
#  image: cznic/armhf-ubuntu:16.04
#  stage: build
#  script:
#    - make -k all
#  tags:
#    - docker
#    - linux
#    - arm

#arm_test:
#  image: armv7/armhf-ubuntu:16.04
#  stage: test
#  script:
#    - make -k check
#  tags:
#    - docker
#    - linux
#    - arm
