language: c
os:
    - linux
    - osx
compiler:
    - clang
notifications:
    email:
        on_success: change
        on_failure: change
    slack:
        rooms: cznic:xNJmvHU2xu2aGtN7Y2eqHKoD
        on_success: change
        on_failure: change
matrix:
    fast_finish: true
    allow_failures:
        - os: osx
env:
    global:
        - PKG_CONFIG_PATH="${HOME}/.local/lib/pkgconfig"
        - PATH="${HOME}/.local/bin:/usr/local/bin:${PATH}"
        - CFLAGS="${CFLAGS} -O0 -g -fPIC -DNDEBUG"
        - LD_LIBRARY_PATH="${HOME}/.local/lib"
        - DYLD_LIBRARY_PATH="${HOME}/.local/lib"
        - MAKEOPTS="-j2"
before_script:
    - ./scripts/bootstrap-depends.sh ${HOME}/.local
script:
    - make ${MAKEOPTS} install check COVERAGE=1 PREFIX=${HOME}/.local
after_success:
    - test $TRAVIS_OS_NAME = linux && coveralls -i lib -x ".c" --gcov-options '\-lp'
sudo: false
cache:
    directories:
    - ${HOME}/.local
    - ${HOME}/.cache/pip
