language: c
compiler:
    - gcc
env:
    global:
        - PKG_CONFIG_PATH="${HOME}/fakeroot/lib/pkgconfig"
        - LDFLAGS="-L${HOME}/fakeroot/lib"
before_script:
    - ./scripts/bootstrap-depends.sh ${HOME}/fakeroot
script:
    - autoreconf -i
    - ./configure
    - make
    - make check
sudo: false
cache:
    directories:
    - ${HOME}/fakeroot
