language: c
compiler:
    - gcc
env:
    global:
        - PATH="${PATH}:${HOME}/.local/bin"
        - PKG_CONFIG_PATH="${HOME}/fakeroot/lib/pkgconfig"
        - LD_LIBRARY_PATH="${HOME}/fakeroot/lib"
        - CFLAGS="${CFLAGS} -O0 -g -DNDEBUG"
before_script:
    - ./scripts/bootstrap-depends.sh ${HOME}/fakeroot
    - pip install --user travis -r tests/pydnstest/requirements.txt cpp-coveralls
script:
    - make check COVERAGE=1 LDFLAGS="-L${HOME}/fakeroot/lib"
    - coveralls -i lib -x ".c" --gcov-options '\-lp'
sudo: false
cache:
    directories:
    - ${HOME}/fakeroot
    - ${HOME}/.cache/pip
