language: c
os:
    - linux
    - osx
compiler:
    - clang
notifications:
    email:
        on_success: change
        on_failure: change
matrix:
    fast_finish: true
    allow_failures:
        - os: osx
env:
    global:
        - PKG_CONFIG_PATH="${HOME}/.local/lib/pkgconfig"
        - LD_LIBRARY_PATH="${HOME}/.local/lib"
        - DYLD_LIBRARY_PATH="${HOME}/.local/lib"
        - PATH="${PATH}:${HOME}/.local/bin"
        - CFLAGS="${CFLAGS} -O0 -g -DNDEBUG"
before_script:
    - pip install --user travis -r tests/pydnstest/requirements.txt cpp-coveralls
    - ./scripts/bootstrap-depends.sh ${HOME}/.local
script:
    - make ${MAKEOPTS} check COVERAGE=1
after_success:
    - test $TRAVIS_OS_NAME = linux && coveralls -i lib -x ".c" --gcov-options '\-lp'
sudo: false
cache:
    directories:
    - ${HOME}/.local
    - ${HOME}/.cache/pip
